-- ============================================================
--  Migración: actualizar nombres y unidades en catalogo_cw
--  Ejecutar en Supabase → SQL Editor
-- ============================================================

UPDATE public.catalogo_cw SET nombre = 'Anclajes tipo Hilti 1/2 incl. Perforación, perno y Epóxico', unidad = 'UN' WHERE actividad_id = '2.05';
UPDATE public.catalogo_cw SET nombre = 'Anclajes tipo Hilti 3/4 incl. Perforación, perno y Epóxico', unidad = 'UN' WHERE actividad_id = '2.06';
UPDATE public.catalogo_cw SET nombre = 'Anclajes tipo Hilti 1 incl. Perforación, perno y Epóxico', unidad = 'UN' WHERE actividad_id = '2.07';
UPDATE public.catalogo_cw SET nombre = 'Anclajes tipo Hilti 1 1/2 incl. Perforación, perno y Epóxico', unidad = 'UN' WHERE actividad_id = '2.08';
UPDATE public.catalogo_cw SET nombre = 'Sum. e inst. de bandeja portacable MECANO de 10 cm. Semipesada. Inc. Curvas, Soportes, anclajes y accesorios', unidad = 'ml' WHERE actividad_id = '2.09';
UPDATE public.catalogo_cw SET nombre = 'Sum. e inst. de bandeja portacable MECANO de 20 cm. Semipesada. Inc. Curvas, Soportes, anclajes y accesorios', unidad = 'ml' WHERE actividad_id = '2.1';
UPDATE public.catalogo_cw SET nombre = 'Sum. e inst. de bandeja portacable MECANO de 30 cm. Semipesada. Inc. Curvas, Soportes, anclajes y accesorios', unidad = 'ml' WHERE actividad_id = '2.11';
UPDATE public.catalogo_cw SET nombre = 'Sum. e inst. de bandeja portacable MECANO de 40 cm. Semipesada. Inc. Curvas, Soportes, anclajes y accesorios', unidad = 'ml' WHERE actividad_id = '2.12';
UPDATE public.catalogo_cw SET nombre = 'Sum. e inst. de bandeja portacable MECANO de 60 cm. Semipesada. Inc. Curvas, Soportes, anclajes y accesorios', unidad = 'ml' WHERE actividad_id = '2.13';
UPDATE public.catalogo_cw SET nombre = 'Sum. e inst. Puente horizontal MECANO para guía de onda. Incl. Pedestales de concreto al piso. De 30 cm. de ancho', unidad = 'ml' WHERE actividad_id = '2.14';
UPDATE public.catalogo_cw SET nombre = 'Puente horizontal MECANO para guía de onda. Incl. Pedestales de concreto al piso. De 40 cm. de ancho', unidad = 'ml' WHERE actividad_id = '2.15';
UPDATE public.catalogo_cw SET nombre = 'Puente horizontal MECANO para guía de onda. Incl. Pedestales de concreto al piso. De 60 cm. de ancho', unidad = 'ml' WHERE actividad_id = '2.16';
UPDATE public.catalogo_cw SET nombre = 'Sum. E Instalación de escalera de acceso a=0,40m. A torre', unidad = 'ml' WHERE actividad_id = '2.28';
UPDATE public.catalogo_cw SET nombre = 'Soportes tipo mastil para antenas celulares. h=3,00 m con diametro de 21/2', unidad = 'Un' WHERE actividad_id = '2.2925';
UPDATE public.catalogo_cw SET nombre = 'Soportes tipo mastil para antenas celulares. h=3,00 m con diametro de 3', unidad = 'Un' WHERE actividad_id = '2.2926';
UPDATE public.catalogo_cw SET nombre = 'Soportes tipo mastil para antenas celulares. h=3,50 m con diametro de 3', unidad = 'Un' WHERE actividad_id = '2.2927';
UPDATE public.catalogo_cw SET nombre = 'Soportes tipo mastil para antenas celulares. h=3,50 m (Tubo de 2 1/2)', unidad = 'Un' WHERE actividad_id = '2.2936';
UPDATE public.catalogo_cw SET nombre = 'Soportes tipo mastil para antenas celulares. h=3,50 m (Tubo de 3)', unidad = 'Un' WHERE actividad_id = '2.2937';
UPDATE public.catalogo_cw SET nombre = 'Soportes tipo mastil en torre/monopolo para antenas celulares. h=1,50 m. Diametro 2 1/2', unidad = 'Un' WHERE actividad_id = '2.2940';
UPDATE public.catalogo_cw SET nombre = 'Soportes tipo mastil en torre/monopolo para antenas celulares. h=2.00 m. Diametro 2 1/2', unidad = 'Un' WHERE actividad_id = '2.2941';
UPDATE public.catalogo_cw SET nombre = 'Soportes tipo mastil en torre/monopolo para antenas celulares. h=2,50 m. Diametro 2 1/2', unidad = 'Un' WHERE actividad_id = '2.2942';
UPDATE public.catalogo_cw SET nombre = 'Soportes tipo mastil en torre/monopolo para antenas celulares. h=3,00 m. Diametro 2 1/2', unidad = 'Un' WHERE actividad_id = '2.2943';
UPDATE public.catalogo_cw SET nombre = 'Soportes tipo mastil en torre/monopolo para antenas celulares. h=3,50 m. Diametro 2 1/2', unidad = 'Un' WHERE actividad_id = '2.2944';
UPDATE public.catalogo_cw SET nombre = 'Soportes tipo mastil en torre/monopolo para antenas celulares. h=3,50 m. Diametro 3', unidad = 'Un' WHERE actividad_id = '2.2949';
UPDATE public.catalogo_cw SET nombre = 'soporte anclado para system mudule altura max de 2 m; incluye anclajes o concreto para fijación del soporte', unidad = 'Un' WHERE actividad_id = '2.2961';
UPDATE public.catalogo_cw SET nombre = 'soporte tipo mastil adosado al autoportante de 1 m X 21/2 con una separacion de 0,5 m con respecto al mastil principal del autoportante', unidad = 'Un' WHERE actividad_id = '2.2962';
UPDATE public.catalogo_cw SET nombre = 'Limpieza y Descapote', unidad = 'M2' WHERE actividad_id = '3.01';
UPDATE public.catalogo_cw SET nombre = 'Placa en concreto 3000 psi.e=0,20m. (para caseta de equipos con mamposteria u otros (Inc. Refuerzo, formaleta)', unidad = 'M2' WHERE actividad_id = '3.08';
UPDATE public.catalogo_cw SET nombre = 'Terminales pala No.6 para aterrizar estructuras metalicas', unidad = 'Un' WHERE actividad_id = '6.12';
UPDATE public.catalogo_cw SET nombre = 'Sum. E inst. Coraza tipo americano de 1/2 Incl. Accesorios', unidad = 'ml' WHERE actividad_id = '7.07';
UPDATE public.catalogo_cw SET nombre = 'Sum. E inst. Coraza tipo americano de 3/4 Inc. Accesorios', unidad = 'ml' WHERE actividad_id = '7.08';
UPDATE public.catalogo_cw SET nombre = 'Sum. E inst. Coraza tipo americano de 1 Inc. Accesorios', unidad = 'ml' WHERE actividad_id = '7.09';
UPDATE public.catalogo_cw SET nombre = 'Sum. E inst. Coraza tipo americano de 1 1/2 Inc. Acceosrios', unidad = 'ml' WHERE actividad_id = '7.10';
UPDATE public.catalogo_cw SET nombre = 'Sum. E inst. Coraza tipo americano de 2 Inc. Accesorios', unidad = 'ml' WHERE actividad_id = '7.11';
UPDATE public.catalogo_cw SET nombre = 'Sum. E inst. cable No.6', unidad = 'ml' WHERE actividad_id = '7.31';
UPDATE public.catalogo_cw SET nombre = 'Platina de cobre macizo Cal 1/4 L= 60 cm x A=10 cm para conexión de tierras con sus aisladores de fijación y 44 perforaciones de 1/4 en tres filas (Incluye instalacion)', unidad = 'Un' WHERE actividad_id = '8.02';
UPDATE public.catalogo_cw SET nombre = 'Platina de cobre macizo Cal 1/4 L= 30 cm x A=3 para conexión de tierras con sus aisladores de fijación y 18 perforaciones de 1/4 en tres filas de 6 perforaciones.', unidad = 'Un' WHERE actividad_id = '8.03';
UPDATE public.catalogo_cw SET nombre = 'Platina de cobre macizo Cal 1/4 L= 30 cm x A=10 cm para conexión de tierras con sus aisladores de fijación y 22 perforaciones de 1/4 en tres filas. (Incluye instalacion)', unidad = 'Un' WHERE actividad_id = '8.04';
UPDATE public.catalogo_cw SET nombre = 'Platina de cobre macizo Cal 1/4 L= 15cm x A=3 para conexión de tierras con sus aisladores de fijación y 9 perforaciones en tres filas de 1/4', unidad = 'Un' WHERE actividad_id = '8.05';
UPDATE public.catalogo_cw SET nombre = 'Reubicacion de barraje de tierras (no importa el tamaño) hacia otra posicion, No incluye cable 1/0 para instalar pues se asume que se utiliza el existente', unidad = 'UN' WHERE actividad_id = '8.09';
UPDATE public.catalogo_cw SET nombre = 'Reacomodacion de guias de onda en escalerilla vertical de ancho entre 40 cm y 60 cm (Incluye amarres posteriores, perforaciones para hangers, snaps in, etc)', unidad = 'ML' WHERE actividad_id = '9.01';
UPDATE public.catalogo_cw SET nombre = 'Impermeabilización de placas de cubierta con manto zetal', unidad = 'm2' WHERE actividad_id = '9.11';
UPDATE public.catalogo_cw SET nombre = 'Impermeabilización de placas de cubierta con manto edil real AT 3mm', unidad = 'm2' WHERE actividad_id = '9.12';
UPDATE public.catalogo_cw SET nombre = 'Aseo, remate y limpieza general', unidad = 'GB' WHERE actividad_id = '9.13';
UPDATE public.catalogo_cw SET nombre = 'Reubicacion de soportes en torre', unidad = 'Un' WHERE actividad_id = '10.05';
UPDATE public.catalogo_cw SET nombre = 'Reubicacion de soportes en cubierta', unidad = 'Un' WHERE actividad_id = '10.06';
UPDATE public.catalogo_cw SET nombre = 'Escalera de gato. Fabricada en tubo de ¾” soldada y pintada, que irá fijada con pernos a la pared del cuarto para permitir el acceso a la cubierta donde se ubicaran las antenas.', unidad = 'ml' WHERE actividad_id = '10.07';
UPDATE public.catalogo_cw SET nombre = 'Extension adicional (instalada) para pasos de guias de onda. Largo de extension 25 cm, sin incluir la longitud de fijacion por paso. Incluye perforaciones para hangers (de 3/4 y de 9 mm, separacion entre perforaciones de 3/4 10 cm, separacion entre perforaciones de 9 mm y 3/4 5 cm. Se pagara por ml de torre o monopolo', unidad = 'ml' WHERE actividad_id = '10.09';
UPDATE public.catalogo_cw SET nombre = 'Aterrizaje en cable desnudo No 6 hasta cada una de la estructuras metálicas (soportes, escalerilla, etc.). (Incluye accesorios de fijación, terminales de ojo, etc..)', unidad = 'ml' WHERE actividad_id = '10.11';
UPDATE public.catalogo_cw SET nombre = 'Suministro e instalación corona de seguridad galvanizada con accesorios de fijación. Un (1) juego de collarín, con puntas soldadas en varilla 3/8 x 60 cm para postes.', unidad = 'UN' WHERE actividad_id = '11.02';
UPDATE public.catalogo_cw SET nombre = 'Suministro e instalación soporte galvanizado para antena celular con accesorios de fijación. Dos (2) juegos de collarín con tubo, platinas soldadas.', unidad = 'UN' WHERE actividad_id = '11.03';
UPDATE public.catalogo_cw SET nombre = 'Suministro e instalación soporte galvanizado para antena de microondas con accesorios de fijación. Dos (2) juegos de collarín con tubo, platina soldadas, tubo de 1 1/2 x 60 cm', unidad = 'UN' WHERE actividad_id = '11.04';
UPDATE public.catalogo_cw SET nombre = 'Suministro e instalación platina de cobre 10 x 15 cm con base, aisladores y accesorios de fijación.', unidad = 'UN' WHERE actividad_id = '11.05';
UPDATE public.catalogo_cw SET nombre = 'Desmonte de corona de seguridad galvanizada con accesorios de fijación. Un (1) juego de collarín, con puntas soldadas en varilla 3/8 x 60 cm para postes.', unidad = 'UN' WHERE actividad_id = '11.06';
UPDATE public.catalogo_cw SET nombre = 'Desmonte de soporte galvanizado para antena celular con accesorios de fijación. Dos (2) juegos de collarín con tubo, platinas soldadas.', unidad = 'UN' WHERE actividad_id = '11.07';
UPDATE public.catalogo_cw SET nombre = 'Desmonte de soporte galvanizado para antena de microondas con accesorios de fijación. Dos (2) juegos de collarín con tubo, platina soldadas, tubo de 1 1/2 x 60 cm', unidad = 'UN' WHERE actividad_id = '11.08';
UPDATE public.catalogo_cw SET nombre = 'Desmonte de platina de cobre 10 x 15 cm con base, aisladores y accesorios de fijación.', unidad = 'UN' WHERE actividad_id = '11.09';
UPDATE public.catalogo_cw SET nombre = 'Sum. Bus Bar Acero Galvanizado 650x50x5 mm con 24 perforaciones de 11mm 2 perforaciones de 16 mm en los extremos con todos sus accesorios.', unidad = 'UN' WHERE actividad_id = '12.01';
UPDATE public.catalogo_cw SET nombre = 'Inst. Bus Bar Acero Galvanizado 650x50x5 mm con 24 perforaciones de 11mm 2 perforaciones de 16 mm en los extremos con todos sus accesorios.', unidad = 'UN' WHERE actividad_id = '12.02';
UPDATE public.catalogo_cw SET nombre = 'Sum Bus Bar Acero Galvanizado 300x75x5 mm con 12 perforaciones de 11mm 2 perforaciones de 16 mm en los extremos con todos sus accesorios.', unidad = 'UN' WHERE actividad_id = '12.03';
UPDATE public.catalogo_cw SET nombre = 'Inst. Bus Bar Acero Galvanizado 300x75x5 mm con 12 perforaciones de 11mm 2 perforaciones de 16 mm en los extremos con todos sus accesorios.', unidad = 'UN' WHERE actividad_id = '12.04';
UPDATE public.catalogo_cw SET nombre = 'Sum. Bus Bar Acero Galvanizado 650x75x5 mm con 24 perforaciones de 11mm 2 perforaciones de 16 mm en los extremos con todos sus accesorios.', unidad = 'UN' WHERE actividad_id = '12.05';
UPDATE public.catalogo_cw SET nombre = 'Inst. Bus Bar Acero Galvanizado 650x75x5 mm con 24 perforaciones de 11mm 2 perforaciones de 16 mm en los extremos con todos sus accesorios.', unidad = 'UN' WHERE actividad_id = '12.06';
UPDATE public.catalogo_cw SET nombre = 'Sum. Bus Bar Acero Galvanizado 600x50x5 mm con 24 perforaciones de 11mm 2 perforaciones de 16 mm en los extremos con todos sus accesorios.', unidad = 'UN' WHERE actividad_id = '12.07';
UPDATE public.catalogo_cw SET nombre = 'Inst. Bus Bar Acero Galvanizado 600x50x5 mm con 24 perforaciones de 11mm 2 perforaciones de 16 mm en los extremos con todos sus accesorios.', unidad = 'UN' WHERE actividad_id = '12.08';
UPDATE public.catalogo_cw SET nombre = 'Sum. Bus Bar Acero Galvanizado 300x50x5 mm con 12 perforaciones de 11mm 2 perforaciones de 16 mm en los extremos con todos sus accesorios.', unidad = 'UN' WHERE actividad_id = '12.09';
UPDATE public.catalogo_cw SET nombre = 'Inst. Bus Bar Acero Galvanizado 300x50x5 mm con 12 perforaciones de 11mm 2 perforaciones de 16 mm en los extremos con todos sus accesorios.', unidad = 'UN' WHERE actividad_id = '12.1';
UPDATE public.catalogo_cw SET nombre = 'Sum. Bus Bar de Acero Galvanizado 350x75x5 mm con 12 perforaciones de 11mm y 2 perforaciones de 16 mm en los extremos con todos sus accesorios.', unidad = 'UN' WHERE actividad_id = '12.11';
UPDATE public.catalogo_cw SET nombre = 'Inst. Bus Bar de Acero Galvanizado 350x75x5 mm con 12 perforaciones de 11mm y 2 perforaciones de 16 mm en los extremos con todos sus accesorios.', unidad = 'UN' WHERE actividad_id = '12.12';
UPDATE public.catalogo_cw SET nombre = 'Sum. Platinas de cobre de 15 x 4 cm con perforaciones', unidad = 'UN' WHERE actividad_id = '12.13';
UPDATE public.catalogo_cw SET nombre = 'Ins. Platinas de cobre de 15 x 4 cm con perforaciones', unidad = 'UN' WHERE actividad_id = '12.14';
UPDATE public.catalogo_cw SET nombre = 'Sum. Cable de acero galvanizado 1/2 7 hilos', unidad = 'm' WHERE actividad_id = '12.24';
UPDATE public.catalogo_cw SET nombre = 'Ins. Cable de acero galvanizado 1/2 7 hilos', unidad = 'm' WHERE actividad_id = '12.25';
UPDATE public.catalogo_cw SET nombre = 'Sum. Cable de acero inxidable calibre 3/8 7 hilos', unidad = 'm' WHERE actividad_id = '12.26';
UPDATE public.catalogo_cw SET nombre = 'Ins. Cable de acero inxidable calibre 3/8 7 hilos', unidad = 'm' WHERE actividad_id = '12.27';
UPDATE public.catalogo_cw SET nombre = 'Sum. Cable de acero galvanizado 1/2 6 x 19 ó 6 x 26', unidad = 'm' WHERE actividad_id = '12.28';
UPDATE public.catalogo_cw SET nombre = 'Sum. Cable de acero inxidable calibre 1/2 2x26 hilos (ES EL MISMO DE 6X19 O 6X26)', unidad = 'm' WHERE actividad_id = '12.29';
UPDATE public.catalogo_cw SET nombre = 'Sum e inst. Tornillos', unidad = 'UN' WHERE actividad_id = '12.77';
UPDATE public.catalogo_cw SET nombre = 'Sum. E Inst Terminales de cobre estañado de un ojo 4/0', unidad = 'UN' WHERE actividad_id = '12.78';
UPDATE public.catalogo_cw SET nombre = 'Sum. E inst Terminales de cobre estañado de doble ojo 2/0', unidad = 'UN' WHERE actividad_id = '12.79';
UPDATE public.catalogo_cw SET nombre = 'Sum. E inst Terminales de cobre estañado de doble ojo 1/0', unidad = 'UN' WHERE actividad_id = '12.8';
UPDATE public.catalogo_cw SET nombre = 'Sum. E inst Terminales de cobre estañado de doble ojo 2/0', unidad = 'UN' WHERE actividad_id = '12.81';
UPDATE public.catalogo_cw SET nombre = 'Sum e inst. Tornillos partidos (2/0)', unidad = 'UN' WHERE actividad_id = '12.85';
UPDATE public.catalogo_cw SET nombre = 'Sum. Cinta 3M', unidad = 'UN' WHERE actividad_id = '12.86';
UPDATE public.catalogo_cw SET nombre = 'Sum. Cinta de encauchetar', unidad = 'UN' WHERE actividad_id = '12.87';
UPDATE public.catalogo_cw SET nombre = 'PLATINA GALVANIZADA PARA ALARMAS DE 35CM X 15 CM', unidad = 'un' WHERE actividad_id = '12.9';
UPDATE public.catalogo_cw SET nombre = 'PLATINAS 20*10 GALVANIZADA DE 12 PERFORACIONES', unidad = 'un' WHERE actividad_id = '12.91';
UPDATE public.catalogo_cw SET nombre = 'CONECTOR BIMETALICO DE 2/0 A 4/0', unidad = 'un' WHERE actividad_id = '12.92';
UPDATE public.catalogo_cw SET nombre = 'CONECTOR BIMETALICO DE 2/0', unidad = 'un' WHERE actividad_id = '12.93';
UPDATE public.catalogo_cw SET nombre = 'CONECTOR BIMETALICO 3/0', unidad = 'un' WHERE actividad_id = '12.94';
UPDATE public.catalogo_cw SET nombre = 'CONECTOR BIMETALICO 4/0', unidad = 'un' WHERE actividad_id = '12.95';
UPDATE public.catalogo_cw SET nombre = 'TORNILLO PARTIDO 4/0', unidad = 'un' WHERE actividad_id = '12.96';
UPDATE public.catalogo_cw SET nombre = 'TERMINAL BRISTOL(2/0)', unidad = 'un' WHERE actividad_id = '12.97';
UPDATE public.catalogo_cw SET nombre = 'Tornillo partido 2/0', unidad = 'un' WHERE actividad_id = '12.98';
UPDATE public.catalogo_cw SET nombre = 'PLATINAS 300*140 GALVANIZADA DE 12 PERFORACIONES', unidad = 'un' WHERE actividad_id = '12.1_1';
UPDATE public.catalogo_cw SET nombre = 'PLATINAS 300*80* GALVANIZADA DE 12 PERFORACIONES', unidad = 'un' WHERE actividad_id = '12.101';
UPDATE public.catalogo_cw SET nombre = 'INSTALACION DE GABINETES', unidad = 'UN' WHERE actividad_id = '12.102';
UPDATE public.catalogo_cw SET nombre = 'PERFIL OMEGA CAL 12 DIMENSIONES 12 ALTO X10 BASE PESTAÑA DE 5 CM', unidad = 'ML' WHERE actividad_id = '12.103';
UPDATE public.catalogo_cw SET nombre = 'Diseño y Suministro de collarines en platina y varilla en punta de 3/8 según diseño enviado por Comcel. Incluye galvanizado en caliente y esparragos ajustables a las diferentes medidas de los postes en concreto', unidad = 'UN' WHERE actividad_id = '12.108';
UPDATE public.catalogo_cw SET nombre = 'Transporte de Materiales T1--En las Ciudades de Bogotá, Medellín, Cali, Pereira, Manizales, Bucaramanga, Barranquilla, Cartagena y su área Metropolitana ( ver Anexo 1.  Ciudades principales y su área metropolitana).', unidad = 'GB' WHERE actividad_id = '14.1';
UPDATE public.catalogo_cw SET nombre = 'Transporte de materiales T2-- Sitios ubicados en capitales de departamento y su área metropolitana no incluidos en T1', unidad = 'GB' WHERE actividad_id = '14.2';
UPDATE public.catalogo_cw SET nombre = 'Transporte de materiales T3-- En los departamentos de Vichada, Guainia,Guaviare, Vaupes ,Putumayo , Caqueta , Amazonas y San Andres y Providencia.', unidad = 'GB' WHERE actividad_id = '14.3';
UPDATE public.catalogo_cw SET nombre = 'Transporte de personal T1--En las Ciudades de Bogotá, Medellín, Cali, Pereira, Manizales, Bucaramanga, Barranquilla, Cartagena y su área Metropolitana el valor del transporte está incluido en el valor de la actividad ( ver Anexo 1.  Ciudades principales y su área metropolitana).', unidad = 'Valor / Sitio' WHERE actividad_id = '15.1';
UPDATE public.catalogo_cw SET nombre = 'Transporte de personal T2-- Sitios ubicados en capitales de departamento y su área metropolitana no incluidos en T1.', unidad = 'Valor / Sitio' WHERE actividad_id = '15.2';
UPDATE public.catalogo_cw SET nombre = 'Transporte de personal T3--Sitios por fuera de T1 y T2 que se pueda acceder por vía vehicular.', unidad = 'Valor / Sitio' WHERE actividad_id = '15.3';
UPDATE public.catalogo_cw SET nombre = 'Transporte de personal T4-- Sitio Rural con acceso difícil - Caminos y/o trochas.', unidad = 'Valor / Sitio' WHERE actividad_id = '15.4';

-- 106 items actualizados
