-- ============================================================
--  Carga masiva sitios Ingetel 2026 (67 sitios)
--  Ejecutar en Supabase SQL Editor
-- ============================================================

-- ── 1. Actualizar es_interna en subcontratistas ─────────────
UPDATE public.subcontratistas SET es_interna = true WHERE lc = 'ALDAIR EDILBERTO MENESES ORTEGA';
UPDATE public.subcontratistas SET es_interna = true WHERE lc = 'DUMMIE';
UPDATE public.subcontratistas SET es_interna = true WHERE lc = 'DUVER JOSE DIAZ CAMPO';
UPDATE public.subcontratistas SET es_interna = true WHERE lc = 'EDISON ALEXANDER GARCIA RUIZ';
UPDATE public.subcontratistas SET es_interna = true WHERE lc = 'EDISON ANDRES CANO VARGAS';
UPDATE public.subcontratistas SET es_interna = true WHERE lc = 'GABRIEL ENRIQUE HERNANDEZ DELGADO';
UPDATE public.subcontratistas SET es_interna = true WHERE lc = 'JAIDER GUTIERREZ VEGA';
UPDATE public.subcontratistas SET es_interna = true WHERE lc = 'JECSON FESTES';
UPDATE public.subcontratistas SET es_interna = true WHERE lc = 'JHON ALVARO MUÑOZ';
UPDATE public.subcontratistas SET es_interna = false WHERE lc = 'JONATAN SNEIDER ANGARITA CHARRY';
UPDATE public.subcontratistas SET es_interna = true WHERE lc = 'JUAN CAMILO TIMANA HIDALGO';
UPDATE public.subcontratistas SET es_interna = true WHERE lc = 'JUAN DAVID CAMAYO PINTO';
UPDATE public.subcontratistas SET es_interna = true WHERE lc = 'JULIO CESAR DURAN VELASQUEZ';
UPDATE public.subcontratistas SET es_interna = true WHERE lc = 'ROBIN TARCICIO PINCHAO';

-- ── 2. Insertar sitios ──────────────────────────────────────
INSERT INTO public.sitios
  (id, nombre, tipo, ciudad, region, lc, cat, estado, actividades, costos, cr_subc_excluded)
VALUES
  ('CAL.La Base', 'CAL.La Base', 'TI', 'Ciudad_Principal', 'R3 – Suroccidente', 'ROBIN TARCICIO PINCHAO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CAL.Prado Norte-2', 'CAL.Prado Norte-2', 'TI', 'Ciudad_Principal', 'R3 – Suroccidente', 'ROBIN TARCICIO PINCHAO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 9}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CAU.Sucre', 'CAU.Sucre', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'EDISON ALEXANDER GARCIA RUIZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CAU.Balboa', 'CAU.Balboa', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JECSON FESTES', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('VAL.Panorama', 'VAL.Panorama', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'DUVER JOSE DIAZ CAMPO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('ANT.Concepcion', 'ANT.Concepcion', 'TI', 'Ciudad_Intermedia', 'R2 – Noroccidente', 'GABRIEL ENRIQUE HERNANDEZ DELGADO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('ANT.Cisneros Berrio', 'ANT.Cisneros Berrio', 'TI', 'Ciudad_Intermedia', 'R2 – Noroccidente', 'GABRIEL ENRIQUE HERNANDEZ DELGADO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('ANT.Cedeno', 'ANT.Cedeno', 'TI', 'Ciudad_Intermedia', 'R2 – Noroccidente', 'JAIDER GUTIERREZ VEGA', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CAU.Dominguillo', 'CAU.Dominguillo', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'JULIO CESAR DURAN VELASQUEZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('VAL.Loboguerrero-2', 'VAL.Loboguerrero-2', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'JULIO CESAR DURAN VELASQUEZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CAU.Paletara', 'CAU.Paletara', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'JHON ALVARO MUÑOZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 9}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Guayacana', 'NAR.Guayacana', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JUAN CAMILO TIMANA HIDALGO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CAU.El Palo', 'CAU.El Palo', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'DUVER JOSE DIAZ CAMPO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CAU.Mondomo', 'CAU.Mondomo', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'EDISON ALEXANDER GARCIA RUIZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CAL.Decepaz-2', 'CAL.Decepaz-2', 'TI', 'Ciudad_Principal', 'R3 – Suroccidente', 'ROBIN TARCICIO PINCHAO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Candelillas', 'NAR.Candelillas', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JUAN CAMILO TIMANA HIDALGO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('VAL.Yumbo-2', 'VAL.Yumbo-2', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'DUVER JOSE DIAZ CAMPO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 9}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 9}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CAD.La Rochela', 'CAD.La Rochela', 'TI', 'Ciudad_Secundaria', 'R2 – Noroccidente', 'GABRIEL ENRIQUE HERNANDEZ DELGADO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 9}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('MED.Moscu', 'MED.Moscu', 'TI', 'Ciudad_Principal', 'R2 – Noroccidente', 'JAIDER GUTIERREZ VEGA', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 10}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('ANT.Santo Domingo', 'ANT.Santo Domingo', 'TI', 'Ciudad_Intermedia', 'R2 – Noroccidente', 'JAIDER GUTIERREZ VEGA', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('ANT.Pabellon', 'ANT.Pabellon', 'TI', 'Ciudad_Intermedia', 'R2 – Noroccidente', 'JUAN DAVID CAMAYO PINTO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CAD.La Habana', 'CAD.La Habana', 'TI', 'Ciudad_Intermedia', 'R2 – Noroccidente', 'GABRIEL ENRIQUE HERNANDEZ DELGADO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 11}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 9}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Potosi', 'NAR.Potosi', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JULIO CESAR DURAN VELASQUEZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 8}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Rosal del Monte', 'NAR.Rosal del Monte', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'DUVER JOSE DIAZ CAMPO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 9}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Ipiales-1', 'NAR.Ipiales-1', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JULIO CESAR DURAN VELASQUEZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 15}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 9}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Imues', 'NAR.Imues', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JUAN CAMILO TIMANA HIDALGO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CAL.Retiro', 'CAL.Retiro', 'TI', 'Ciudad_Principal', 'R3 – Suroccidente', 'ROBIN TARCICIO PINCHAO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('QUB.Quibdo Medrano', 'QUB.Quibdo Medrano', 'TI', 'Ciudad_Intermedia', 'R2 – Noroccidente', 'ALDAIR EDILBERTO MENESES ORTEGA', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 10}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('QUB.Batallon', 'QUB.Batallon', 'TI', 'Ciudad_Intermedia', 'R2 – Noroccidente', 'GABRIEL ENRIQUE HERNANDEZ DELGADO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CAU.Alfonso', 'CAU.Alfonso', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'EDISON ALEXANDER GARCIA RUIZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('PUT.La Hormiga', 'PUT.La Hormiga', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'EDISON ALEXANDER GARCIA RUIZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 13}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('PUT.Coembi', 'PUT.Coembi', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'ROBIN TARCICIO PINCHAO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 8}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Mallama', 'NAR.Mallama', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'DUVER JOSE DIAZ CAMPO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('ANT.La Union Madera', 'ANT.La Union Madera', 'TI', 'Ciudad_Intermedia', 'R2 – Noroccidente', 'GABRIEL ENRIQUE HERNANDEZ DELGADO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('PUT.Santiago', 'PUT.Santiago', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'EDISON ALEXANDER GARCIA RUIZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 8}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('QUB.El Silencio', 'QUB.El Silencio', 'TI', 'Ciudad_Intermedia', 'R2 – Noroccidente', 'ALDAIR EDILBERTO MENESES ORTEGA', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 8}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('HUI.Potrerillos', 'HUI.Potrerillos', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JUAN DAVID CAMAYO PINTO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 10}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Iscuande', 'NAR.Iscuande', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'EDISON ALEXANDER GARCIA RUIZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Guachaves', 'NAR.Guachaves', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JHON ALVARO MUÑOZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Salahonda', 'NAR.Salahonda', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'EDISON ANDRES CANO VARGAS', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 9}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('HUI.Santana', 'HUI.Santana', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'JULIO CESAR DURAN VELASQUEZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('PUT.Colon', 'PUT.Colon', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'ROBIN TARCICIO PINCHAO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('PUT.Orito-2', 'PUT.Orito-2', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'JUAN CAMILO TIMANA HIDALGO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 11}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Tamana', 'NAR.Tamana', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JUAN CAMILO TIMANA HIDALGO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('PAS.Batallon', 'PAS.Batallon', 'TI', 'Ciudad_Secundaria', 'R3 – Suroccidente', 'DUVER JOSE DIAZ CAMPO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('IBG.Sexta Brigada', 'IBG.Sexta Brigada', 'TI', 'Ciudad_Secundaria', 'R3 – Suroccidente', 'JHON ALVARO MUÑOZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 8}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 8}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NEI.Exito', 'NEI.Exito', 'TI', 'Ciudad_Secundaria', 'R3 – Suroccidente', 'EDISON ALEXANDER GARCIA RUIZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Roberto Payan', 'NAR.Roberto Payan', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'DUMMIE', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Cruz de Amarillo', 'NAR.Cruz de Amarillo', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JUAN DAVID CAMAYO PINTO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('HUI.Pacarni', 'HUI.Pacarni', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'ROBIN TARCICIO PINCHAO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 8}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CHO.Carmen de Atrato-2', 'CHO.Carmen de Atrato-2', 'TI', 'Dificil Acceso', 'R2 – Noroccidente', 'ALDAIR EDILBERTO MENESES ORTEGA', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Tambo', 'NAR.Tambo', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JUAN CAMILO TIMANA HIDALGO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 8}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('FLO.Porvenir-2', 'FLO.Porvenir-2', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JONATAN SNEIDER ANGARITA CHARRY', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CAU.Muralla', 'CAU.Muralla', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'DUMMIE', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 9}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Tumaco-14', 'NAR.Tumaco-14', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JULIO CESAR DURAN VELASQUEZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('CAU.Santa Catalina', 'CAU.Santa Catalina', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'DUMMIE', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 9}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('PAS.Terminal', 'PAS.Terminal', 'TI', 'Ciudad_Secundaria', 'R3 – Suroccidente', 'DUMMIE', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 9}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('VAL.Aeropuerto-2', 'VAL.Aeropuerto-2', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JULIO CESAR DURAN VELASQUEZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 8}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('ARM.La Maria', 'ARM.La Maria', 'TI', 'Ciudad_Secundaria', 'R2 – Noroccidente', 'DUMMIE', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('NAR.Tumaco-8', 'NAR.Tumaco-8', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'DUVER JOSE DIAZ CAMPO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 12}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('PAS.RB Aranda', 'PAS.RB Aranda', 'TI', 'Ciudad_Secundaria', 'R3 – Suroccidente', 'DUVER JOSE DIAZ CAMPO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('PER.Japon', 'PER.Japon', 'TI', 'Ciudad_Intermedia', 'R2 – Noroccidente', 'JUAN DAVID CAMAYO PINTO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 9}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 7}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('PER.Pimpollo', 'PER.Pimpollo', 'TI', 'Ciudad_Intermedia', 'R2 – Noroccidente', 'ALDAIR EDILBERTO MENESES ORTEGA', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 10}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('POP.Centro', 'POP.Centro', 'TI', 'Ciudad_Secundaria', 'R3 – Suroccidente', 'EDISON ALEXANDER GARCIA RUIZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 12}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 8}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('PUT.San Miguel', 'PUT.San Miguel', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'ROBIN TARCICIO PINCHAO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 9}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 6}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('TOL.Rio Blanco', 'TOL.Rio Blanco', 'TI', 'Ciudad_Intermedia', 'R3 – Suroccidente', 'JUAN CAMILO TIMANA HIDALGO', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 1}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 4}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb),
  ('VAL.Ceilan', 'VAL.Ceilan', 'TI', 'Dificil Acceso', 'R3 – Suroccidente', 'JHON ALVARO MUÑOZ', 'A', 'pre', '[{"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_BB", "cant": 3}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "DESMONTE_RF", "cant": 5}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "IMP_RF", "cant": 2}, {"sec": "MODERNIZACION", "tipo": "BASE", "id": "PM", "cant": 1}]'::jsonb, '{}'::jsonb, '[]'::jsonb)
ON CONFLICT (id) DO NOTHING;

-- ── FIN: 67 sitios procesados ────────────────────────────
